language: python

before_install:
    - "sudo apt-get update -qq"
    - "sudo apt-get install -qq sloccount"
    - "pip install tox"
    - "pip install coveralls"
    - "pip install coviolations_app"

script:
    - "tox"

after_success:
    - "coveralls"
    - "covio"

env:
    - TOXENV=py27-django16
    - TOXENV=py33-django16
