language: python

python:
    - "2.7"
    - "3.3"

before_install:
    - "sudo apt-get update -qq"
    - "sudo apt-get install -qq sloccount"
    - "pip install coveralls"
    - "pip install coviolations_app"

install:
    - "pip install -r requirements/test.txt"

script:
    - "tox"

after_success:
    - "coveralls"
    - "covio"
